name: Package updates

on:
  schedule:
    - cron: "0 0 * * 1"

  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  package-updates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: gundotio/package-updates/python@v1
        with:
          title: (Deps) Package updates
          commit: Package updates
          branch: package-updates
          reviewers: |
            stevelacey
            wadewilliams
